/*  
 * JCE Editor               2.2.0
 * @package                 JCE
 * @url                     http://www.joomlacontenteditor.net
 * @copyright               Copyright (C) 2006 - 2012 Ryan Demmer. All rights reserved
 * @license                 GNU/GPL Version 2 or later - http://www.gnu.org/licenses/gpl-2.0.html
 * @date                    14 May 2012
 * @Translation				Mihàly Marti alias Sarki - www.joomlatutos.com
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * NOTE : Les fichiers Javascript sont compressés (sans espace) pour accélérer le chargement. Vous pouvez remettre le code en page par l'outil disponible sur ce lien : http://jsbeautifier.org/
 */
tinyMCE.addI18n('fr.imgmanager_ext_dlg',{missing_alt:"Êtes-vous sûr de vouloir insérer une image sans inclure de description? Sans elle, l'image sera invisible pour les sytèmes de lecture (malvoyants, etc.), pour les navigateurs dont l'affichage des images est désactivé et, pour les moteurs de recherche!",delta_width:0,delta_height:0,'0':'Original','-90':'90&deg; Droite','90':'90&deg; Gauche','180':'180&deg;','vertical':'Rotation verticale','horizontal':'Rotation horizontale','view_images':'Affichage Miniatures','view_list':'Affichage Liste','use_thumbnail':'Utiliser la miniature associée?','resize':'Redimensionner','rotate':'Rotation','proportional':'Proportionnel','cropped':'Carré','mode':'Mode','quality':'Qualité','size':'Taille','thumbnail':'Miniature','transform':'Modifier','width':'Largeur','height':'Hauteur','create_thumbnail':'Créer une miniature','delete_thumbnail':'Effacer la miniature','message_images':'Cliquez sur une image pour voir ses propriétés et l\'insérer son URL dans le champ. CTRL+Clic pour séléctionner plusieurs images','message_list':'Cliquez sur le nom de l\'image pour voir ses propriétés et l\'insérer. CTRL+Clic pour séléctionner plusieurs images','no_src':'Pour insérer une image, veuillez la sélectionner ou indiquer son adresse URL','no_popup_src':'Pour afficher une image en popup, veuillez la sélectionner ou indiquer son adresse URL','upload_resize_tip':'Redimensionner::Redimensionner selon les largeur et hauteur spécifiées en maintenant les proportionnalités','upload_thumbnail_tip':'Miniature::Créer une miniature selon les largeur et hauteur spécifiées en maintenant les proportionnalités. Si Recadrer est coché, la vignette sera recadrée pour s\'adapter aux dimensions spécifiées','upload_thumbnail_crop':'Recadrer','upload_thumbnail_crop_tip':'Recadrer::Recadrer la miniature pour s\'adapter  aux dimensions spécifiées','greyscale':'Gris','sepia':' Sépia','invert':'Négatif','lighten':'Éclaircissement','darken':'Assombrissement','saturate':'Saturation','desaturate':'Désaturation','threshold':'Seuil','halftone':'Demi-teinte','create_thumbnail_failed':'Impossible de créer la vignette','original':'Originale','display':'Afficher'});