#DROP TABLE IF EXISTS `#__jcrm_accounts`;
CREATE TABLE IF NOT EXISTS `#__jcrm_accounts` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `parent_id` int(12) DEFAULT NULL,
  `date_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `date_entered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_user_id` int(12) NOT NULL DEFAULT '-1',
  `created_by` int(12) NOT NULL DEFAULT '-1',
  `state` tinyint(4) NOT NULL DEFAULT '1',
  `country_id` varchar(3) DEFAULT NULL,
  `name` varchar(256) DEFAULT NULL,
  `logo_name` varchar(24) DEFAULT NULL,
  `phone_fax` varchar(32) DEFAULT NULL,
  `phone_account` varchar(32) DEFAULT NULL,
  `account_type` varchar(128) DEFAULT NULL,
  `account_speciality` varchar(256) DEFAULT NULL,
  `cours_list` text,
  `degrees_list` text,
  `research_areas_list` text,
  `annual_appropriations` varchar(4) DEFAULT NULL,
  `address_street` varchar(512) DEFAULT NULL,
  `address_street_2` varchar(256) DEFAULT NULL,
  `address_postalcode` varchar(24) DEFAULT NULL,
  `address_city` varchar(56) DEFAULT NULL,
  `address_state` varchar(56) DEFAULT NULL,
  `address_country` varchar(128) DEFAULT NULL,
  `website` varchar(256) DEFAULT NULL,
  `director_name` varchar(256) DEFAULT NULL,
  `director_email` varchar(139) DEFAULT NULL,
  `location` varchar(136) DEFAULT NULL,
  `economic_information` varchar(212) DEFAULT NULL,
  `number_student_places` varchar(3) DEFAULT NULL,
  `number_students` varchar(6) DEFAULT NULL,
  `code_account` varchar(13) DEFAULT NULL,
  `faculties_list` varchar(269) DEFAULT NULL,
  `areas_of_excellence` text,
  `campus_info` text,
  `agreements_list` text,
  `practical_info` text,
  `comment` text,
  `partner_esa` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `country_id` (`country_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3298 DEFAULT CHARSET=utf8

#DROP TABLE IF EXISTS `#__jcrm_contacts`;
CREATE TABLE IF NOT EXISTS `#__jcrm_contacts` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `date_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `date_entered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_user_id` int(12) DEFAULT NULL,
  `created_by` int(12) DEFAULT NULL,
  `state` tinyint(1) DEFAULT NULL,
  `country_code` varchar(19) DEFAULT NULL,
  `account_name` varchar(93) DEFAULT NULL,
  `department` varchar(153) DEFAULT NULL,
  `primary_address_street` varchar(162) DEFAULT NULL,
  `primary_address_postalcode` varchar(82) DEFAULT NULL,
  `primary_address_state` varchar(10) DEFAULT NULL,
  `primary_address_city` varchar(29) DEFAULT NULL,
  `salutation` varchar(69) DEFAULT NULL,
  `first_name` varchar(27) DEFAULT NULL,
  `last_name` varchar(128) DEFAULT NULL,
  `title` varchar(224) DEFAULT NULL,
  `phone_work` varchar(138) DEFAULT NULL,
  `phone_fax` varchar(96) DEFAULT NULL,
  `email` varchar(63) DEFAULT NULL,
  `website` varchar(56) DEFAULT NULL,
  `mailing` tinyint(1) DEFAULT NULL,
  `account_id` int(12) DEFAULT NULL,
  `comment` varchar(68) DEFAULT NULL,
  `referent_postgradutate` tinyint(1) DEFAULT NULL,
  `referent_esa_name` varchar(22) DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL,
  `contact_type` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3760 DEFAULT CHARSET=utf8

#DROP TABLE IF EXISTS `#__jcrm_countries`;
CREATE TABLE IF NOT EXISTS `#__jcrm_countries` (
  `id` int(3) NOT NULL,
  `name` varchar(30) DEFAULT NULL,
  `zone` varchar(11) DEFAULT NULL,
  `continent` varchar(28) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

