/*  
 * JCE Editor               2.2.0
 * @package                 JCE
 * @url                     http://www.joomlacontenteditor.net
 * @copyright               Copyright (C) 2006 - 2012 Ryan Demmer. All rights reserved
 * @license                 GNU/GPL Version 2 or later - http://www.gnu.org/licenses/gpl-2.0.html
 * @date                    14 May 2012
 * @Translation				Mihàly Marti alias Sarki - www.joomlatutos.com
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * NOTE : Les fichiers Javascript sont compressés (sans espace) pour accélérer le chargement. Vous pouvez remettre le code en page par l'outil disponible sur ce lien : http://jsbeautifier.org/
 */
tinyMCE.addI18n('fr.fullpage_dlg',{title:"Propriétés du document",meta_tab:"Général",appearance_tab:"Apparence",advanced_tab:"Avancé",meta_props:"Méta information",langprops:"Langue et encodage",meta_title:"Titre",meta_keywords:"Mots clés",meta_description:"Description",meta_robots:"Robots",doctypes:"Doctype",langcode:"Code langue",langdir:"Direction d'écriture",ltr:"Gauche à droite",rtl:"Droite à gauche",xml_pi:"Déclaration XML",encoding:"Encodage des caractères",appearance_bgprops:"Propriétés du fond",appearance_marginprops:"Marge de page",appearance_linkprops:"Couleur des liens",appearance_textprops:"Propriétés du texte",bgcolor:"Couleur de fond",bgimage:"Image de fond",left_margin:"Marge gauche",right_margin:"Marge droite",top_margin:"Marge haut",bottom_margin:"Marge bas",text_color:"Couleur du texte",font_size:"Taille d'écriture",font_face:"Police d'écriture",link_color:"Couleur du lien",hover_color:"Couleur lien au survol",visited_color:"Couleur lien visité",active_color:"Couleur lien actif",textcolor:"Coleur",fontsize:"Taille d'écriture",fontface:"Police d'écriture",meta_index_follow:"Index et liens suivis",meta_index_nofollow:"Index, liens non suivis",meta_noindex_follow:"Sans index mais liens suivis",meta_noindex_nofollow:"Sans index et liens non suivis",appearance_style:"Stylesheet and style properties",stylesheet:"Feuille de style",style:"Style",author:"Auteur",copyright:"Copyright",add:"Ajouter un nouvel élément",remove:"Supprimer l'élément",moveup:"Déplacer l'élément vers le haut",movedown:"Déplacer l'élément vers le bas",head_elements:"Élément d'en-tête",info:"Information",add_title:"Titre de l'entête",add_meta:"Métadonnée",add_script:"Script",add_style:"Style",add_link:"Lien",add_base:"Élément de base",add_comment:"Commentaire",title_element:"Titre",script_element:"Script",style_element:"Style",base_element:"Élément de base",link_element:"Lien",meta_element:"Métadonnée",comment_element:"Commentaire",src:"Src",language:"Langue",href:"Href",target:"Cible",type:"Type",charset:"Charset",defer:"Defer",media:"Media",properties:"Propriétés",name:"Nom",value:"Valeur",content:"Contenu",rel:"Rel",rev:"Rev",hreflang:"Href lang",general_props:"Général",advanced_props:"Avancé"});